version: "3.7"



services:
  application:
    build:
      context: ..
      dockerfile: Dockerfile
  php-cli:
    build:
      dockerfile: Dockerfile
      context: ..
    depends_on:
      - webserver
    volumes:
      - ../:/mnt/app
    restart: always
    links:
      - redis
      - webserver
  webserver:
    container_name: airflow-webserver
    restart: always
    build:
      context: ..
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 30s
      retries: 5

  airflow-init:
    container_name: airflow-init
    entrypoint: /bin/bash
    build:
      context: ..
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
  redis:
    image: redis:4.0
    container_name: app_pump
    restart: always
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
    volumes:
      - ./redis/data:/data
    ports:
      - "6382:6379"
