version: "3.7"

services:
  php-cli:
    build:
      dockerfile: docker/Dockerfile
      context: ./..
    volumes:
      - ../:/mnt/app
    restart: always

  redis:
    image: redis:4.0
    container_name: dump_app
    restart: always
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
    volumes:
      - ./redis/data:/data
    ports:
      - "6383:6379"
