version: "3.7"
networks:
  dump-pump:
    driver: "bridge"

services:
  php-cli:
    build:
      dockerfile: Dockerfile
      context: ..
    volumes:
      - ../:/mnt/app
    restart: always
    networks:
      - dump-pump
